[mypy]
strict = True
disallow_untyped_defs = True
disallow_untyped_calls = True
ignore_missing_imports = True
plugins = pandera.mypy, pydantic.mypy
exclude = (ppxml2db|mutants)

[mypy-ppxml2db.*]
ignore_errors = True