name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: [ "3.13", "3.14" ]

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: true

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
        cache: 'poetry'

    - name: Install Dependencies
      run: make install

    - name: Run Code Checks
      run: make check

    - name: Running Tests
      run: make test

  build:
    name: Build Package
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: true
        fetch-depth: 0  # we need everything for poetry-dynamic-versioning

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - uses: actions/setup-python@v6
      with:
        python-version: "3.14"
        cache: 'poetry'

    - name: Install Dependencies
      run: make install ARGS="--no-root"

    - name: Build Package
      run: make build

    - name: Install the built wheel
      run: |
        pip install dist/*.whl

    - name: Run the built wheel
      run: |
        pp-terminal --version

    - name: Upload Package
      uses: actions/upload-artifact@v7
      with:
        name: python-package-distributions
        path: dist/

  publish-to-testpypi:
    name: Publish to TestPyPI
    needs: build
    runs-on: ubuntu-latest
    environment: test-pypi

    permissions:
      id-token: write

    steps:
      - name: Download Package
        uses: actions/download-artifact@v8
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b  # release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-to-pypi:
    name: Publish to PyPI
    needs: publish-to-testpypi
    runs-on: ubuntu-latest
    environment: pypi

    permissions:
      id-token: write

    steps:
      - name: Download Package
        uses: actions/download-artifact@v8
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b  # release/v1